language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sairaj2119/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sairaj2119/react-test npm run test
    
after_success:
  - docker build -t sairaj2119/multi-client ./client
  - docker build -t sairaj2119/multi-nginx ./nginx
  - docker build -t sairaj2119/multi-server ./server
  - docker build -t sairaj2119/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sairaj2119/multi-client
  - docker push sairaj2119/multi-nginx
  - docker push sairaj2119/multi-server
  - docker push sairaj2119/multi-worker